Fixed the file not found error in build
```
Traceback (most recent call last):
782  File "<string>", line 1, in <module>
783FileNotFoundError: [Errno 2] No such file or directory: './pytorch-lightning/requirements/extra.txt'
784error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
```

The whole directory was moved under pytorch-lightning i.e.
pytorch-lightning
└── pytorch-lightning-*